# Generated by Django 2.2.1 on 2019-05-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('root', models.CharField(max_length=30, verbose_name='管理员')),
            ],
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=30, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='option',
            name='number',
            field=models.IntegerField(verbose_name='个数'),
        ),
        migrations.AlterField(
            model_name='option',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poor.vote', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='problem',
            field=models.CharField(max_length=100, verbose_name='问题'),
        ),
    ]
